### PR TITLE
libkmod: use memory-mapped access to modules.builtin.modinfo

### PR DESCRIPTION
**Pull request by o2cheretnyi**
Sometimes the read access to huge modules.builtin.modinfo file via tons of pread() calls can cause speed degradation during 'depmod' command's execution, so the accessing of memory-mapped file's area is faster.

Signed-off-by: Oleksandr Ocheretnyi <oocheret@cisco.com>

### CODE REVIEW

**Comment by evelikov** [comment]
@o2cheretnyi some notes from a first-time contributor to kmod:

Have you measured the impact of using mmap? Quantifying with concrete numbers in the commit message is always appreciated.

Would it make sense to `flock` for the duration of the mmap? Some projects do so, although I'm not sure if it'll be useful here.

Last but not least - consider sending the patch to the ML listed in the README. HTH o/

**Comment by o2cheretnyi** [comment]
@evelikov , I have some comparison table based on Yocto's core-image-full-cmdline image run on QEMU. However I need to note that all measurements were done with kmod's version 29 where I'd observed this drawback first time.
 ```
'depmod' execution time during Yocto's core-image-full-cmdline image run on QEMU
+-----------------------------+-------------------------------+-------------------------------+
 |                             |          pread() calls        |          mmap() call          |
+-----------------------------+-------------------------------+-------------------------------+
 |        time, seconds        |         ~ 45-120              |            ~ 1-7              |
+-----------------------------+-------------------------------+-------------------------------+
```
Conclusion: these changes do not play much role when we are using kmod with version 30 what resolves this issue with https://github.com/kmod-project/kmod/commit/0246e06340df292b5dda4bc00e24cc9ae894e881

**Comment by lucasdemarchi** [comment]
depmod 30 has changes explicitly to handle this issue. See https://github.com/kmod-project/kmod/blob/master/NEWS#L8-L11

could you check if upgrading to kmod 30 helps?

**Comment by lucasdemarchi** [comment]
Oh... missed your last phrase in the comment. Yeah, I don't think we really need to move to mmap as just avoiding the open/read/close multiple times is sufficient.

**Pull request closed without merging**
